-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES_SUM * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN(
    SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) S
    ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC