-- 코드를 입력하세요
SELECT MONTH(H.START_DATE) AS MONTH,
        H.CAR_ID,
        COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN(
    SELECT CAR_ID, COUNT(*) AS C_RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
    AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    ) C
    ON H.CAR_ID = C.CAR_ID
    AND C.C_RECORDS >=5
WHERE H.START_DATE >= '2022-08-01'
  AND H.START_DATE < '2022-11-01'
GROUP BY MONTH(H.START_DATE), H.CAR_ID
ORDER BY MONTH ASC, H.CAR_ID DESC
