SELECT ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN(
    SELECT FISH_TYPE, MAX(LENGTH) as MAXLENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) M
    ON I.FISH_TYPE = M.FISH_TYPE
    AND I.LENGTH = M.MAXLENGTH
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY ID